import Foundation

// MARK: - Sample Onsen Dataset (日本各地の代表的な温泉)
enum SampleData {
    static let onsens: [Onsen] = [
        // ─── 北海道 ───
        Onsen(name: "登別温泉",         nameReading: "のぼりべつおんせん",
              address: "北海道登別市登別温泉町",          prefecture: "北海道",
              latitude: 42.4449,  longitude: 141.1055,
              description: "日本でも屈指の温泉地。地獄谷をはじめとする9種類もの泉質が楽しめる多彩な温泉。",
              onsenType: .hotSpring, springQuality: "硫黄泉・食塩泉など9種",
              facilities: ["露天風呂", "大浴場", "足湯", "地獄谷散策"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        Onsen(name: "洞爺湖温泉",        nameReading: "とうやこおんせん",
              address: "北海道虻田郡洞爺湖町洞爺湖温泉",   prefecture: "北海道",
              latitude: 42.5458,  longitude: 140.7974,
              description: "洞爺湖のほとりに広がる温泉地。湖と有珠山を一望できるロケーション抜群の温泉。",
              onsenType: .resort, springQuality: "塩化物泉",
              facilities: ["露天風呂", "大浴場", "レストラン", "観光船"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        Onsen(name: "定山渓温泉",        nameReading: "じょうざんけいおんせん",
              address: "北海道札幌市南区定山渓温泉",        prefecture: "北海道",
              latitude: 42.9781,  longitude: 141.1061,
              description: "札幌近郊に位置する温泉地。渓谷美と豊富な湯量が魅力。「札幌の奥座敷」と呼ばれる。",
              onsenType: .hotSpring, springQuality: "ナトリウム塩化物泉",
              facilities: ["露天風呂", "大浴場", "川床", "渓谷散策"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        // ─── 東北 ───
        Onsen(name: "蔵王温泉",          nameReading: "ざおうおんせん",
              address: "山形県山形市蔵王温泉",             prefecture: "山形県",
              latitude: 38.3597,  longitude: 140.4369,
              description: "強酸性の硫黄泉で有名な蔵王の温泉地。スキーリゾートとしても人気。湯の色が乳白色に変わる神秘的な温泉。",
              onsenType: .hotSpring, springQuality: "強酸性硫黄泉",
              facilities: ["露天風呂", "大浴場", "足湯", "スキー場"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        Onsen(name: "鳴子温泉",          nameReading: "なるこおんせん",
              address: "宮城県大崎市鳴子温泉",             prefecture: "宮城県",
              latitude: 38.7313,  longitude: 140.7264,
              description: "東北最大の温泉郷。9種類の泉質が楽しめる「泉質の博物館」とも呼ばれる温泉地。こけしの産地でも有名。",
              onsenType: .hotSpring, springQuality: "9種類の多彩な泉質",
              facilities: ["露天風呂", "大浴場", "足湯", "こけし工房"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        // ─── 関東 ───
        Onsen(name: "草津温泉",          nameReading: "くさつおんせん",
              address: "群馬県吾妻郡草津町草津",            prefecture: "群馬県",
              latitude: 36.6194,  longitude: 138.5951,
              description: "日本三名泉のひとつ。毎分3万リットルを超える自然湧出量日本一を誇る。湯畑が観光スポットとして有名。",
              onsenType: .hotSpring, springQuality: "酸性硫黄泉",
              facilities: ["湯畑", "西の河原露天風呂", "大浴場", "時間湯"],
              openingHours: "施設により異なる", entryFee: "無料〜有料", hasParking: true),

        Onsen(name: "箱根温泉",          nameReading: "はこねおんせん",
              address: "神奈川県足柄下郡箱根町湯本",        prefecture: "神奈川県",
              latitude: 35.2302,  longitude: 139.1063,
              description: "富士山を望む関東屈指の温泉リゾート。多彩な泉質と豊富な宿泊施設、美術館も充実。",
              onsenType: .resort, springQuality: "アルカリ性単純温泉など多種",
              facilities: ["露天風呂", "大浴場", "美術館", "ロープウェイ"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        Onsen(name: "伊東温泉",          nameReading: "いとうおんせん",
              address: "静岡県伊東市",                     prefecture: "静岡県",
              latitude: 34.9652,  longitude: 139.1028,
              description: "伊豆半島に位置する温泉地。湯量が豊富で共同浴場も多数。漁師町の雰囲気と海の幸も魅力。",
              onsenType: .hotSpring, springQuality: "アルカリ性単純温泉",
              facilities: ["共同浴場", "露天風呂", "海水浴場", "釣り"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        Onsen(name: "伊豆長岡温泉",      nameReading: "いずながおかおんせん",
              address: "静岡県伊豆の国市長岡",              prefecture: "静岡県",
              latitude: 35.0298,  longitude: 138.9387,
              description: "富士山と駿河湾を一望できる高台の宿が多い温泉地。夜景の美しさでも知られる。",
              onsenType: .hotSpring, springQuality: "アルカリ性単純温泉",
              facilities: ["露天風呂", "展望浴場", "大浴場", "富士山眺望"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        // ─── 信越・北陸 ───
        Onsen(name: "野沢温泉",          nameReading: "のざわおんせん",
              address: "長野県下高井郡野沢温泉村",          prefecture: "長野県",
              latitude: 36.9178,  longitude: 138.4360,
              description: "無料で入れる13か所の外湯が点在する昔ながらの温泉村。スキーリゾートとしても人気。",
              onsenType: .hotSpring, springQuality: "単純硫黄泉",
              facilities: ["13か所の外湯", "スキー場", "野沢菜漬け体験"],
              openingHours: "外湯は24時間（一部時間制限あり）", entryFee: "外湯は寸志制（無料）", hasParking: true),

        Onsen(name: "和倉温泉",          nameReading: "わくらおんせん",
              address: "石川県七尾市和倉町",                prefecture: "石川県",
              latitude: 37.0738,  longitude: 136.9990,
              description: "能登半島の付け根に位置する温泉地。日本最高クラスの旅館「加賀屋」で知られる。ナトリウム・カルシウム塩化物泉。",
              onsenType: .hotSpring, springQuality: "ナトリウム・カルシウム塩化物泉",
              facilities: ["総湯（公衆浴場）", "露天風呂", "能登の食材", "観光船"],
              openingHours: "総湯7:00〜21:00", entryFee: "総湯 大人470円", hasParking: true),

        Onsen(name: "山代温泉",          nameReading: "やましろおんせん",
              address: "石川県加賀市山代温泉",              prefecture: "石川県",
              latitude: 36.2968,  longitude: 136.3477,
              description: "北陸最大規模の温泉地「加賀温泉郷」のひとつ。総湯（共同浴場）の文化が根付く歴史ある温泉地。",
              onsenType: .hotSpring, springQuality: "ナトリウム・カルシウム塩化物泉",
              facilities: ["総湯", "古総湯", "露天風呂", "加賀工芸"],
              openingHours: "総湯6:00〜22:00", entryFee: "総湯 大人470円", hasParking: true),

        // ─── 東海 ───
        Onsen(name: "下呂温泉",          nameReading: "げろおんせん",
              address: "岐阜県下呂市湯之島",                prefecture: "岐阜県",
              latitude: 35.8046,  longitude: 137.2454,
              description: "日本三名泉のひとつ。アルカリ性の高い湯は「美人の湯」としても有名。飛騨川沿いに広がる温泉地。",
              onsenType: .hotSpring, springQuality: "アルカリ性単純温泉",
              facilities: ["露天風呂", "足湯", "合掌造り集落", "温泉博物館"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        // ─── 関西 ───
        Onsen(name: "有馬温泉",          nameReading: "ありまおんせん",
              address: "兵庫県神戸市北区有馬町",            prefecture: "兵庫県",
              latitude: 34.7966,  longitude: 135.2464,
              description: "日本三名泉のひとつ・日本最古の温泉地のひとつ。金泉（含鉄・塩化物泉）と銀泉（炭酸泉）の二種類が楽しめる。",
              onsenType: .hotSpring, springQuality: "含鉄・塩化物泉（金泉）/炭酸水素塩泉（銀泉）",
              facilities: ["金の湯", "銀の湯", "露天風呂", "太閤の湯"],
              openingHours: "金の湯8:00〜22:00（第2・4火曜休）", entryFee: "金の湯 大人800円", hasParking: true),

        Onsen(name: "城崎温泉",          nameReading: "きのさきおんせん",
              address: "兵庫県豊岡市城崎町湯島",            prefecture: "兵庫県",
              latitude: 35.6235,  longitude: 134.8156,
              description: "柳の並木と石畳の風情ある街並みが有名な温泉地。7つの外湯を浴衣で巡る「外湯めぐり」が人気。",
              onsenType: .hotSpring, springQuality: "ナトリウム・カルシウム塩化物泉",
              facilities: ["7つの外湯", "露天風呂", "外湯めぐり手形", "カニ料理"],
              openingHours: "外湯7:00〜23:00（施設により異なる）", entryFee: "外湯めぐり手形 大人1,500円", hasParking: true),

        // ─── 中国・四国 ───
        Onsen(name: "道後温泉",          nameReading: "どうごおんせん",
              address: "愛媛県松山市道後湯之町",            prefecture: "愛媛県",
              latitude: 33.8530,  longitude: 132.7869,
              description: "日本最古の温泉のひとつ。夏目漱石の小説「坊っちゃん」の舞台。重要文化財の道後温泉本館が象徴。",
              onsenType: .hotSpring, springQuality: "アルカリ性単純温泉",
              facilities: ["道後温泉本館", "飛鳥乃湯泉", "椿の湯", "道後公園"],
              openingHours: "6:00〜23:00", entryFee: "大人 神の湯720円〜", hasParking: true),

        // ─── 九州 ───
        Onsen(name: "別府温泉",          nameReading: "べっぷおんせん",
              address: "大分県別府市",                      prefecture: "大分県",
              latitude: 33.2780,  longitude: 131.4940,
              description: "日本一の湧出量を誇る温泉都市。8種類の「地獄」巡り観光と多彩な泉質が魅力。",
              onsenType: .hotSpring, springQuality: "8種類の多彩な泉質",
              facilities: ["地獄めぐり", "砂風呂", "共同浴場", "温泉プール"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        Onsen(name: "黒川温泉",          nameReading: "くろかわおんせん",
              address: "熊本県阿蘇郡南小国町満願寺黒川",    prefecture: "熊本県",
              latitude: 33.1040,  longitude: 131.1572,
              description: "九州山地の奥地に位置する秘湯。自然との調和を大切にした風情ある温泉地。露天風呂めぐり手形が人気。",
              onsenType: .hotSpring, springQuality: "硫酸塩泉・塩化物泉など",
              facilities: ["露天風呂めぐり手形", "24か所の旅館露天風呂", "渓谷散策"],
              openingHours: "施設により異なる", entryFee: "入湯手形 大人1,500円（3か所）", hasParking: true),

        Onsen(name: "由布院温泉",        nameReading: "ゆふいんおんせん",
              address: "大分県由布市湯布院町川上",           prefecture: "大分県",
              latitude: 33.2611,  longitude: 131.3640,
              description: "由布岳の麓に広がるおしゃれな温泉リゾート。アート・グルメ・温泉が融合した大人気の観光地。",
              onsenType: .resort, springQuality: "単純温泉",
              facilities: ["金鱗湖", "アートギャラリー", "フランス料理", "露天風呂"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        Onsen(name: "指宿温泉",          nameReading: "いぶすきおんせん",
              address: "鹿児島県指宿市",                    prefecture: "鹿児島県",
              latitude: 31.2529,  longitude: 130.6318,
              description: "砂むし温泉で有名な温泉地。天然の砂浜に湧く温泉で全身を温める砂風呂体験が名物。",
              onsenType: .hotSpring, springQuality: "ナトリウム塩化物泉",
              facilities: ["砂むし温泉", "大浴場", "露天風呂", "錦江湾眺望"],
              openingHours: "8:30〜21:00（砂むし会館）", entryFee: "砂むし 大人1,100円", hasParking: true),

        // ─── 東京都内 ───
        Onsen(name: "東京染井温泉 SAKURA", nameReading: "とうきょうそめいおんせんさくら",
              address: "東京都豊島区駒込5-4-24",            prefecture: "東京都",
              latitude: 35.7394,  longitude: 139.7417,
              description: "染井吉野桜発祥の地・駒込にある天然温泉スパ。都心のオアシスとして人気。",
              onsenType: .spa, springQuality: "ナトリウム塩化物泉",
              facilities: ["大浴場", "露天風呂", "岩盤浴", "食事処", "仮眠室"],
              phoneNumber: "03-5907-5566",
              openingHours: "10:00〜23:00", regularHoliday: "第3火曜日",
              entryFee: "大人 平日1,100円・土休日1,320円", hasParking: false),

        Onsen(name: "大江戸温泉物語 東京",  nameReading: "おおえどおんせんものがたりとうきょう",
              address: "東京都江東区青海2-6-3",             prefecture: "東京都",
              latitude: 35.6263,  longitude: 139.7780,
              description: "江戸の町並みを再現した大型温泉テーマパーク。地下1400mから湧き出る天然温泉。",
              onsenType: .spa, springQuality: "ナトリウム塩化物泉（強塩泉）",
              facilities: ["大浴場", "露天風呂", "フードコート", "縁日広場", "岩盤浴"],
              openingHours: "11:00〜翌9:00（最終入館翌7:00）",
              entryFee: "大人 1,980円〜（時間帯により異なる）", hasParking: true),

        // ─── 追加のピックアップ温泉 ───
        Onsen(name: "熱海温泉",          nameReading: "あたみおんせん",
              address: "静岡県熱海市",                      prefecture: "静岡県",
              latitude: 35.1028,  longitude: 139.0736,
              description: "東京から最も近い温泉リゾート。相模湾を望む景勝地で、多くの旅館・ホテルが立ち並ぶ。",
              onsenType: .resort, springQuality: "塩化物泉・硫酸塩泉など",
              facilities: ["露天風呂", "大浴場", "海水浴場", "熱海城", "海鮮グルメ"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        Onsen(name: "鬼怒川温泉",        nameReading: "きぬがわおんせん",
              address: "栃木県日光市鬼怒川温泉",             prefecture: "栃木県",
              latitude: 36.7893,  longitude: 139.6710,
              description: "鬼怒川渓谷沿いに旅館が立ち並ぶ関東の温泉地。ラフティングなどアウトドアも楽しめる。",
              onsenType: .hotSpring, springQuality: "アルカリ性単純温泉",
              facilities: ["露天風呂", "大浴場", "ラフティング", "鬼怒川温泉ロープウェイ"],
              openingHours: "施設により異なる", entryFee: "施設により異なる", hasParking: true),

        Onsen(name: "白浜温泉",          nameReading: "しらはまおんせん",
              address: "和歌山県西牟婁郡白浜町",             prefecture: "和歌山県",
              latitude: 33.6823,  longitude: 135.3680,
              description: "道後・有馬と並ぶ日本三古湯のひとつ。白砂の浜と青い海、豊富な湯量が魅力。",
              onsenType: .hotSpring, springQuality: "塩化物泉",
              facilities: ["崎の湯（露天）", "白良浜", "大浴場", "千畳敷"],
              openingHours: "崎の湯8:00〜19:00", entryFee: "崎の湯 大人510円", hasParking: true),

        Onsen(name: "湯布院温泉 ゆの坪街道", nameReading: "ゆふいんおんせん ゆのつぼかいどう",
              address: "大分県由布市湯布院町川上1560",       prefecture: "大分県",
              latitude: 33.2570,  longitude: 131.3612,
              description: "由布院温泉のメインストリート。おしゃれなカフェや雑貨屋が並ぶ観光客に人気のエリア。",
              onsenType: .dayUse, springQuality: "単純温泉",
              facilities: ["食べ歩き", "スイーツ", "雑貨ショップ", "ギャラリー"],
              openingHours: "店舗により異なる", entryFee: "無料（施設は有料）", hasParking: true),
    ]
}
